Traceback (most recent call last):
  File "C:/Users/MarianoSalem/Desktop/PracticeProject/PythonEssentials/Debugging/Getting_the_traceback.py", line 9, in <module>
    raise Exception("this is the error message.")
Exception: this is the error message.
